name: Generate Snake Game
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Platane/snk@v3
        with:
          github_user_name: Nikhil-Yadav15
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark
            output/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*
          git commit -m "Update snake game animation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
